const example = {
  Product: {
    description: "Example description",
    id: "5284e18fb5baba49d5xxxxxx",
    name: "Cute Ring",
    number_saves: "6",
    number_sold: "0",
    parent_sku: "Cute Bow Ring",
    review_status: "approved",
    removed_by_merchant: False,
    default_shipping_price: "10.5",
    tags: [
      { Tag: { id: "womensring", name: "womens ring" } },
      { Tag: { id: "jewelry", name: "Jewelry" } },
      { Tag: { id: "bow", name: "Bow" } },
    ],
    variants: [
      {
        Variant: {
          color: "green",
          enabled: "True",
          id: "5284e192b111ba49d5xxxxxx",
          product_id: "5284e18fb5baba49d5xxxxxx",
          inventory: "11",
          msrp: "113.9",
          price: "110.9",
          shipping: "10.5",
          localized_price: "660.0",
          localized_shipping: "63.0",
          localized_currency_code: "CNY",
          sku: "AA1",
        },
      },
      {
        Variant: {
          color: "blue",
          enabled: "True",
          id: "5284e19qqqbaba49d5bbbbbb",
          product_id: "5284e18fb5baba49d5xxxxxx",
          inventory: "100",
          msrp: "19.9",
          price: "15.9",
          shipping: "10.5",
          localized_price: "90.0",
          localized_shipping: "63.0",
          localized_currency_code: "CNY",
          sku: "ZZ1",
        },
      },
    ],
  },
};
